"""
Deterministic Synthetic Log Generator for Solr Observability & RCA Demo.

IMPORTANT PROVENANCE NOTE:
The case study did not provide real production Solr or JVM GC logs.
All logs generated by this script are explicitly SYNTHETIC, DETERMINISTIC fixtures
designed to test the parsing, anomaly detection, correlation, and RCA pipeline.
"""

import os
from datetime import datetime, timedelta
from typing import List, Tuple

BASE_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "data", "synthetic")


def ensure_dir(path: str):
    os.makedirs(path, exist_ok=True)


def generate_healthy_scenario(base_time: datetime) -> Tuple[List[str], List[str]]:
    """Scenario 1: Healthy Cluster - Low QTime, minor GCs, no errors."""
    solr_logs = []
    gc_logs = []
    nodes = ["solr-node-1", "solr-node-2", "solr-node-3"]

    for i in range(20):
        t = base_time + timedelta(seconds=i * 5)
        t_str = t.strftime("%Y-%m-%d %H:%M:%S.%f")[:-3]
        node = nodes[i % 3]
        qtime = 15 + (i % 7) * 4  # 15ms - 39ms
        hits = 120 + (i * 13) % 400

        solr_line = (
            f"{t_str} INFO  (qtp108941827-{100+i}) [{node}:8983_solr ecommerce_shard1_replica_n1] "
            f"o.a.s.c.S.Request [ecommerce] webapp=/solr path=/select params={{q=category:electronics&rows=20}} "
            f"hits={hits} status=0 QTime={qtime}"
        )
        solr_logs.append(solr_line)

        if i % 3 == 0:
            gc_t = t.strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "+0000"
            pause_sec = 0.012 + (i % 4) * 0.003  # 12ms - 21ms
            gc_line = (
                f"{gc_t}: [{node}] [GC (Allocation Failure) [PSYoungGen: 524288K->32768K(611840K)] "
                f"1048576K->557056K(2097152K), {pause_sec:.3f} secs] [Times: user=0.04 sys=0.01, real={pause_sec:.2f} secs]"
            )
            gc_logs.append(gc_line)

    return solr_logs, gc_logs


def generate_gc_pressure_scenario(base_time: datetime) -> Tuple[List[str], List[str]]:
    """Scenario 2: JVM Memory Pressure - Escalating heap, Full GC pauses, elevated latency."""
    solr_logs = []
    gc_logs = []
    node = "solr-node-2"

    for i in range(25):
        t = base_time + timedelta(seconds=i * 4)
        t_str = t.strftime("%Y-%m-%d %H:%M:%S.%f")[:-3]
        gc_t = t.strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "+0000"

        # GC pressure escalating
        if i < 8:
            # Baseline
            qtime = 45 + i * 10
            solr_logs.append(
                f"{t_str} INFO  (qtp108941827-{200+i}) [{node}:8983_solr catalog_shard1_replica_n2] "
                f"o.a.s.c.S.Request [catalog] webapp=/solr path=/select params={{q=*:*&facet=true&facet.field=brand}} "
                f"hits=5400 status=0 QTime={qtime}"
            )
            if i % 2 == 0:
                gc_logs.append(
                    f"{gc_t}: [{node}] [GC (Allocation Failure) [PSYoungGen: 500000K->60000K(600000K)] "
                    f"1200000K->800000K(2097152K), 0.035 secs] [Times: user=0.08 sys=0.01, real=0.04 secs]"
                )
        elif i < 18:
            # Escalating Heap and Full GCs
            qtime = 850 + (i - 8) * 350  # QTime jumps to ~4000ms
            solr_logs.append(
                f"{t_str} WARN  (qtp108941827-{200+i}) [{node}:8983_solr catalog_shard1_replica_n2] "
                f"o.a.s.c.S.Request [catalog] webapp=/solr path=/select params={{q=*:*&facet=true&facet.field=all_text_facet}} "
                f"hits=850000 status=0 QTime={qtime}"
            )
            pause_sec = 2.4 + (i - 8) * 0.4  # Pause 2.4s to 6.4s
            gc_logs.append(
                f"{gc_t}: [{node}] [Full GC (Ergonomics) [PSYoungGen: 600000K->580000K(600000K)] "
                f"[PSOldGen: 1450000K->1420000K(1497152K)] 2050000K->2000000K(2097152K), {pause_sec:.3f} secs] "
                f"[Times: user=4.20 sys=0.35, real={pause_sec:.2f} secs]"
            )
        else:
            # Saturation / Timeouts
            qtime = 7500 + (i - 18) * 500
            solr_logs.append(
                f"{t_str} ERROR (qtp108941827-{200+i}) [{node}:8983_solr catalog_shard1_replica_n2] "
                f"o.a.s.h.RequestHandlerBase Request execution failed or timed out. path=/select QTime={qtime}"
            )

    return solr_logs, gc_logs


def generate_solr_failure_scenario(base_time: datetime) -> Tuple[List[str], List[str]]:
    """Scenario 3: Solr Node / Replica Failure - ZK session expiration, replica marked down, connection refused."""
    solr_logs = []
    gc_logs = []
    node = "solr-node-3"

    for i in range(15):
        t = base_time + timedelta(seconds=i * 6)
        t_str = t.strftime("%Y-%m-%d %H:%M:%S.%f")[:-3]

        if i < 4:
            solr_logs.append(
                f"{t_str} INFO  (qtp55123456-{300+i}) [{node}:8983_solr orders_shard2_replica_n3] "
                f"o.a.s.c.S.Request [orders] webapp=/solr path=/select params={{q=cust_id:9921}} hits=4 status=0 QTime=22"
            )
        elif i < 7:
            solr_logs.append(
                f"{t_str} WARN  (zkConnectionWatcherThread) [{node}:8983_solr] "
                f"o.a.s.c.c.ConnectionManager ZooKeeper connection lost or session expired. Attempting reconnect."
            )
        elif i < 11:
            solr_logs.append(
                f"{t_str} ERROR (OverseerStateUpdate) [{node}:8983_solr orders_shard2_replica_n3] "
                f"o.a.s.c.ZkController Marking replica orders_shard2_replica_n3 as DOWN due to missing heartbeat."
            )
        else:
            solr_logs.append(
                f"{t_str} ERROR (qtp55123456-{300+i}) [solr-node-1:8983_solr orders_shard2_replica_n1] "
                f"o.a.s.h.RequestHandlerBase org.apache.solr.client.solrj.SolrServerException: "
                f"Server refused connection at http://solr-node-3:8983/solr/orders_shard2_replica_n3"
            )

    return solr_logs, gc_logs


def generate_query_latency_scenario(base_time: datetime) -> Tuple[List[str], List[str]]:
    """Scenario 4: Query Latency Spike - Unoptimized wildcards / deep paging causing QTime breach."""
    solr_logs = []
    gc_logs = []
    node = "solr-node-1"

    for i in range(18):
        t = base_time + timedelta(seconds=i * 5)
        t_str = t.strftime("%Y-%m-%d %H:%M:%S.%f")[:-3]

        if i < 5:
            solr_logs.append(
                f"{t_str} INFO  (qtp99887766-{400+i}) [{node}:8983_solr products_shard1_replica_n1] "
                f"o.a.s.c.S.Request [products] webapp=/solr path=/select params={{q=laptop}} hits=320 status=0 QTime=38"
            )
        elif i < 12:
            qtime = 2200 + (i - 5) * 800  # 2200ms -> 7000ms
            solr_logs.append(
                f"{t_str} WARN  (qtp99887766-{400+i}) [{node}:8983_solr products_shard1_replica_n1] "
                f"o.a.s.c.S.Request [products] webapp=/solr path=/select params={{q=*a*b*c*&start=50000&rows=1000}} "
                f"hits=1450000 status=0 QTime={qtime}"
            )
        else:
            solr_logs.append(
                f"{t_str} ERROR (qtp99887766-{400+i}) [{node}:8983_solr products_shard1_replica_n1] "
                f"o.a.s.c.SolrCore Query exceeded allowed time limit (timeAllowed=5000ms). partialResults=true QTime=5200"
            )

    return solr_logs, gc_logs


def generate_mixed_incident_scenario(base_time: datetime) -> Tuple[List[str], List[str]]:
    """
    Scenario 5: Mixed Cross-Source Incident (Cascade Failure).
    Node 2 experiences heavy JVM memory pressure -> 4.8s Full GC pause -> 
    Solr query threads timeout on Node 2 -> Node 2 stops heartbeating -> 
    Node 1 fails to route queries to Node 2 replica.
    """
    solr_logs = []
    gc_logs = []

    for i in range(24):
        t = base_time + timedelta(seconds=i * 4)
        t_str = t.strftime("%Y-%m-%d %H:%M:%S.%f")[:-3]
        gc_t = t.strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "+0000"

        # Stage 1: Memory buildup on solr-node-2
        if i == 2:
            gc_logs.append(
                f"{gc_t}: [solr-node-2] [GC (Allocation Failure) [PSYoungGen: 550000K->120000K(600000K)] "
                f"1600000K->1400000K(2097152K), 0.180 secs] [Times: user=0.45 sys=0.03, real=0.18 secs]"
            )
        elif i == 6:
            # Stage 2: Stop-The-World Full GC on solr-node-2 (4.85 seconds pause)
            gc_logs.append(
                f"{gc_t}: [solr-node-2] [Full GC (Ergonomics) [PSYoungGen: 590000K->580000K(600000K)] "
                f"[PSOldGen: 1460000K->1440000K(1497152K)] 2050000K->2020000K(2097152K), 4.850 secs] "
                f"[Times: user=9.10 sys=0.55, real=4.85 secs]"
            )
        
        # Stage 3: Solr query timeout on solr-node-2 during GC pause
        if i == 7:
            solr_logs.append(
                f"{t_str} ERROR (qtp108941827-801) [solr-node-2:8983_solr inventory_shard1_replica_n2] "
                f"o.a.s.h.RequestHandlerBase Request execution timed out waiting for thread lock. QTime=5120"
            )
        elif i == 8:
            solr_logs.append(
                f"{t_str} WARN  (zkCallback-33-thread-1) [solr-node-2:8983_solr] "
                f"o.a.s.c.c.ConnectionManager Our ZooKeeper session timed out during stop-the-world JVM pause."
            )
        elif i == 10:
            solr_logs.append(
                f"{t_str} ERROR (qtp108941827-802) [solr-node-1:8983_solr inventory_shard1_replica_n1] "
                f"o.a.s.c.HttpShardHandler Error querying remote replica http://solr-node-2:8983/solr/inventory_shard1_replica_n2: "
                f"SocketTimeoutException: Read timed out"
            )
        else:
            solr_logs.append(
                f"{t_str} INFO  (qtp108941827-{800+i}) [solr-node-1:8983_solr inventory_shard1_replica_n1] "
                f"o.a.s.c.S.Request [inventory] webapp=/solr path=/select params={{q=sku:98124}} hits=1 status=0 QTime=32"
            )

    return solr_logs, gc_logs


def write_scenario(scenario_name: str, solr_logs: List[str], gc_logs: List[str]):
    scenario_dir = os.path.join(BASE_DIR, scenario_name)
    ensure_dir(scenario_dir)

    solr_file = os.path.join(scenario_dir, "solr.log")
    gc_file = os.path.join(scenario_dir, "jvm_gc.log")

    with open(solr_file, "w", encoding="utf-8") as f:
        f.write("\n".join(solr_logs) + "\n")

    with open(gc_file, "w", encoding="utf-8") as f:
        f.write("\n".join(gc_logs) + "\n")

    print(f"Generated scenario '{scenario_name}': {len(solr_logs)} Solr logs, {len(gc_logs)} GC logs.")


def main():
    base_time = datetime(2026, 9, 8, 10, 0, 0)
    scenarios = {
        "healthy": generate_healthy_scenario(base_time),
        "gc_pressure": generate_gc_pressure_scenario(base_time),
        "solr_failure": generate_solr_failure_scenario(base_time),
        "query_latency": generate_query_latency_scenario(base_time),
        "mixed_incident": generate_mixed_incident_scenario(base_time),
    }

    for name, (solr_logs, gc_logs) in scenarios.items():
        write_scenario(name, solr_logs, gc_logs)


if __name__ == "__main__":
    main()
